### ISSUE TITLE
make install 

### ISSUE THREAD

**Issue by jcldc** [teuben/nemo#6]
make install report : 

Typically you would do the following: (must be in (t)csh)
      ./configure  ....  -- run configure, with lots of options
      **source nemo_end**    -- if you have an *old* NEMO env
      **source nemo_start**  -- load the NEMO environment
      make postconfig    -- basic post configure things
      rehash                -- update search path
      make libs             -- install the libraries

this report should be changed to reflect the new changements in V4.0:
**source nemo_end
source nemo_start**
should be replace by
**source nemo_start.sh**  (if you are running bash)
**source nemo_start.csh** (if you are running csh)

**Comment by teuben** [comment]
this should look a lot better now. I deprecating the nemo_end for now, but anybody can try and convince me to keep it alive. I'd like to argue just open a new fresh shell.

An example configure with a system pgplot  instead of our git version (which works) would be useful to write down somewhere:

configure --with-yapp=pgplot --with-pgplot-prefix=/usr/lib

**Comment by jcldc** [comment]
well, you didn't push yet, I guess...

**Comment by jcldc** [comment]
ok, yes it's better :)
